# Generated by Django 4.1.1 on 2022-11-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_pwd',
            field=models.CharField(max_length=260),
        ),
    ]
